### ISSUE TITLE
EnrollmentListView에서 getFormattedPhoneNumberString에서 문제 발생

### ISSUE THREAD

**Issue by jsh9611** [Team-BUNT/ClassManager#17]
## 개요
- 전화번호에 이상한 번호가 들어온 경우 에러가 앱이 강제로 종료되는 문제가 발생.

## Todo List
- [ ] getFormattedPhoneNumberString에서 올바른 전화번호인지 확인하는 validation 로직을 추가

**Comment by namgeon1106** [comment]
해당 메서드 삭제했고(#16) validation은 웹에서 처리해야 할 문제라서 close할게
